  version: '3.12'

  services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=sqlalchemy
        - POSTGRES_USER=sqlalchemy
        - POSTGRES_PASSWORD=sqlalchemy
    web:
      build: .
      command: python app.py
      volumes:
        - .:/code
      ports:
        - "8000:8000"
      depends_on:
        - db
