  version: '3.12'

  services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=sqlalchemy
        - POSTGRES_USER=os.getenv("POSTGRES_USER")
        - POSTGRES_PASSWORD=os.getenv("POSTGRES_PASSWORD")
    web:
      build: .
      command: python app.py --host=0.0.0.0
      volumes:
        - ./data:/data/db
      ports:
        - "5000:5000"
        - "5432:5432"
      depends_on:
        - db

